# Generated by Django 6.1 on 2026-08-29 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('titulo_previo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título Previo')),
            ],
            options={
                'verbose_name': 'Cursante',
                'verbose_name_plural': 'Cursantes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_syric', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Syric')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Curso')),
                ('id_cohorte_moodle', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Cohorte Moodle')),
                ('arancel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Arancel')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('docentes', models.ManyToManyField(blank=True, related_name='cursos_docente', to=settings.AUTH_USER_MODEL, verbose_name='Docentes')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_preinscripcion_syric', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Preinscripción Syric')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('BECADO_EXENTO', 'Becado / Exento')], default='PENDIENTE', max_length=20, verbose_name='Estado de Pago')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de Pago')),
                ('estado_moodle', models.CharField(choices=[('NO_MATRICULADO', 'No Matriculado'), ('MATRICULADO', 'Matriculado'), ('MAIL_ENVIADO', 'Mail Enviado')], default='NO_MATRICULADO', max_length=20, verbose_name='Estado Moodle')),
                ('estado_academico', models.CharField(choices=[('CURSANDO', 'Cursando'), ('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado'), ('LIBRE', 'Libre')], default='CURSANDO', max_length=20, verbose_name='Estado Académico')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota Final')),
                ('certificado_syric', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GESTIONADO', 'Gestionado'), ('EMITIDO', 'Emitido')], default='PENDIENTE', max_length=20, verbose_name='Certificado Syric')),
                ('fecha_inscripcion', models.DateField(blank=True, null=True, verbose_name='Fecha de Inscripción')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cursante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academico.cursante', verbose_name='Cursante')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academico.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('cursante', 'curso')},
            },
        ),
    ]
