# Generated by Django 6.1 on 2026-08-29 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursante',
            name='titulo_previo',
            field=models.TextField(blank=True, null=True, verbose_name='Título Previo'),
        ),
        migrations.CreateModel(
            name='TituloCursante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Título')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de Título')),
                ('nivel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nivel')),
                ('cursante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='academico.cursante', verbose_name='Cursante')),
            ],
            options={
                'verbose_name': 'Título de Cursante',
                'verbose_name_plural': 'Títulos de Cursante',
                'ordering': ['nombre'],
            },
        ),
    ]
